# Generated by Django 6.0.5 on 2026-05-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(default='candidate123', max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('subjects_json', models.TextField(default='["English"]')),
                ('is_active', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
                ('messaging_paused', models.BooleanField(default=False)),
                ('can_message', models.BooleanField(default=False)),
                ('can_message_override', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('login_count', models.IntegerField(default=0)),
                ('exams_taken', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('group_type', models.CharField(choices=[('general', 'General'), ('subject', 'Subject')], default='general', max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-users', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_only_post', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_groups',
                'ordering': ['group_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], max_length=20)),
                ('user_identifier', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('announcement', 'Announcement'), ('unlock', 'Unlock'), ('system', 'System')], default='message', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='candidate_files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.candidate')),
            ],
            options={
                'db_table': 'candidate_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], max_length=20)),
                ('sender_id', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=200)),
                ('receiver_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], max_length=20)),
                ('receiver_id', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.message')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group', to='api.chatgroup')),
            ],
            options={
                'db_table': 'subject_groups',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='UnlockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_used', models.CharField(max_length=100)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_records', to='api.candidate')),
            ],
            options={
                'db_table': 'unlock_records',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], max_length=20)),
                ('sender_id', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=200)),
                ('receiver_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('group', 'Group')], max_length=20)),
                ('receiver_id', models.CharField(max_length=20)),
                ('audio_file', models.FileField(upload_to='voice_messages/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chatgroup')),
            ],
            options={
                'db_table': 'voice_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], max_length=20)),
                ('sender_id', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_photo', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('file', 'File'), ('announcement', 'Announcement')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatgroup')),
                ('voice_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.voicemessage')),
            ],
            options={
                'db_table': 'group_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
